# Created by Szymon Gniado

version: "3"
services:
  # Include mariadb image
  database:
    image: mariadb
    container_name: liveflock-database
    # Bind named volume - datadir to docker init directory
    # This is to make mariadb initialize database from data directory
    # volumes:
    #   - datadir:/docker-entrypoint-initdb.d
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: /run/secrets/root_password
      MARIADB_DATABASE: /run/secrets/database_name
      MARIADB_USER: /run/secrets/username
      MARIADB_PASSWORD: /run/secrets/user_password
    secrets:
      - root_password
      - database_name
      - username
      - user_password
    ports:
      - 3306:3306
    networks:
      - liveflock
    healthcheck:
      test: ["CMD", "mariadb-check", "-u", "liveflock", "--password=xd", "liveflock", "account"]
      interval: 30s
      timeout: 10s
      retries: 9
  # Include liveflock api image
  service:
    image: tsayero/liveflock-service
    depends_on:
      database:
        condition: service_healthy
    container_name: liveflock-service
    ports:
      - 8080:8080
    networks:
      - liveflock
networks:
  liveflock:
    driver: bridge
# volumes:
#   # Create named volume - datadir that binds /data directory to MariDB init dir
#   datadir:
#     driver_opts:
#       device: database
secrets:
  root_password:
    file: ./root_password.txt
  database_name:
    file: ./database_name.txt
  username:
    file: ./username.txt
  user_password:
    file: ./user_password.txt