# Created by Szymon Gniado

version: "3"
services:
  # Include mariadb image
  database:
    image: mariadb
    container_name: liveflock-database
    # Bind named volume - datadir to docker init directory
    # This is to make mariadb initialize database from data directory
    volumes:
      - datadir:/docker-entrypoint-initdb.d
    # Make mariadb set random root password
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_USER=liveflock
      - MARIADB_PASSWORD=xd
      - MARIADB_DATABASE=liveflock
    networks:
      - liveflock
    healthcheck:
      test: ["CMD", "mariadb-check", "-u", "liveflock", "--password=xd", "liveflock", "account"]
      interval: 1m30s
      timeout: 10s
      retries: 3
  # Include liveflock api image
  api:
    image: tsayero/liveflock-service
    depends_on:
      database:
        condition: service_healthy
    container_name: liveflock-service
    ports:
      - 8080:8080
    networks:
      - liveflock
networks:
  liveflock:
    driver: bridge
volumes:
  # Create named volume - datadir that binds /data directory to MariDB init dir
  datadir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../data
